---
title: "for Bodeplot - 0.1 - 진폭 Magnitude"
format: html
---

```{r}
#| label: 데이터 수집
#| echo: false
df = read.csv('./data/0.1.lvm',sep = "\t",header = F)
df
```

```{r}
#| label: (비어있는) 1열 제거, 1~100행(초기 필요없는 데이터) 제거
#| echo: false

df = df[,2:4] 
df = df[-(1:100),]
df
```

```{r}
#| label: 열 이름 넣어주기

colnames(df) <- c("sec","u","theta")
head(df)
```

```{r}
#| label: time 열 0부터 시작하도록 조정

df[,1]=df[,1]-min(df[,1])
```
```{r}
#| label: time 열 check

head(df)
```

```{r}
#| label: plotting for EDA - 2
#| code-fold: true
plot(df[,1],df[,2],col = 'red',xlim = c(0,50), ylim = c(-1500,200),xlab = "sec",ylab = "location")
par(new = T)
plot(df[,1],df[,3], col = 'blue',xlim = c(0,50), ylim = c(-1500,200),xlab = "",ylab = "")
legend("topright",legend=c("u","theta"),fill=c("red","blue"),cex=1.5)
```

```{r}
#| label: 구간별 최대값과 최소값 차이를 이용하여 진폭 구하기 - 1 데이터 나누기


df_10 = df[df$sec >= 0 & df$sec <= 10, ] # 0 ~ 10초 구간 데이터 얻기
df_20 = df[df$sec >= 10 & df$sec <= 20, ] # 10 ~ 20초 구간 데이터 얻기
df_30 = df[df$sec >= 20 & df$sec <= 30, ] # 20 ~ 30초 구간 데이터 얻기
df_40 = df[df$sec >= 30 & df$sec <= 40, ] # 30 ~ 40초 구간 데이터 얻기
#df_50 = df[df$sec >= 40 & df$sec <= 50, ] # 40 ~ 50초 구간 데이터 얻기
```

```{r}
#| label: 구간별 최대값과 최소값 차이를 이용하여 진폭 구하기 - 2 구간별 진폭 계산

A_10 = max(df_10$u)-min(df_10$u) # input의 진폭
Aa_10= max(df_10$theta)-min(df_10$theta) # output의 진폭

A_20 = max(df_20$u)-min(df_20$u) # input의 진폭
Aa_20= max(df_20$theta)-min(df_20$theta) # output의 진폭

A_30 = max(df_30$u)-min(df_30$u) # input의 진폭
Aa_30= max(df_30$theta)-min(df_30$theta) # output의 진폭

A_40 = max(df_40$u)-min(df_40$u) # input의 진폭
Aa_40= max(df_40$theta)-min(df_40$theta) # output의 진폭

# A_50 = max(df_50$u)-min(df_50$u) # input의 진폭
# Aa_50= max(df_50$theta)-min(df_50$theta) # output의 진폭
```

```{r}
#| label: 구간별 최대값과 최소값 차이를 이용하여 진폭 구하기 - 3 평균 진폭의 진폭비(Magnitude) 계산

A_m=mean(A_10,A_20,A_30,A_40)
Aa_m=mean(Aa_10,Aa_20,Aa_30,Aa_40)

Mag0.1 = Aa_m/A_m
Mag0.1
```
